import { SearchHit } from "@its-types/api/search"

const EXAMPLE_ITEMS: Array<SearchHit> = [
  {
    color: "pink",
    isGiftCard: false,
    link: "www.inthestyle.com/lorna-luxe-pink-park-avenue-satin-piped-long-5pc-gift-set",
    variants: [
      {
        backorder_note: null,
        size: "4",
        color: "beige",
        parent_sku: "LLOTNIG32258",
        qty: 3,
        backorder_label: "Pre Order",
        id: 258921,
        sku: "LLOTNIG32258-4",
        backorder_type: "no_backorder",
      },
      {
        backorder_note: null,
        size: "6",
        color: "beige",
        parent_sku: "LLOTNIG32258",
        qty: 20,
        backorder_label: "Pre Order",
        id: 258922,
        sku: "LLOTNIG32258-6",
        backorder_type: "no_backorder",
      },
      {
        backorder_note: null,
        size: "8",
        color: "beige",
        parent_sku: "LLOTNIG32258",
        qty: 57,
        backorder_label: "Pre Order",
        id: 258923,
        sku: "LLOTNIG32258-8",
        backorder_type: "no_backorder",
      },
      {
        backorder_note: null,
        size: "10",
        color: "beige",
        parent_sku: "LLOTNIG32258",
        qty: 106,
        backorder_label: "Pre Order",
        id: 258924,
        sku: "LLOTNIG32258-10",
        backorder_type: "no_backorder",
      },
      {
        backorder_note: null,
        size: "12",
        color: "beige",
        parent_sku: "LLOTNIG32258",
        qty: 49,
        backorder_label: "Pre Order",
        id: 258925,
        sku: "LLOTNIG32258-12",
        backorder_type: "no_backorder",
      },
      {
        backorder_note: null,
        size: "14",
        color: "beige",
        parent_sku: "LLOTNIG32258",
        qty: 40,
        backorder_label: "Pre Order",
        id: 258926,
        sku: "LLOTNIG32258-14",
        backorder_type: "no_backorder",
      },
      {
        backorder_note: null,
        size: "16",
        color: "beige",
        parent_sku: "LLOTNIG32258",
        qty: 51,
        backorder_label: "Pre Order",
        id: 258927,
        sku: "LLOTNIG32258-16",
        backorder_type: "no_backorder",
      },
      {
        backorder_note: null,
        size: "18",
        color: "beige",
        parent_sku: "LLOTNIG32258",
        qty: 48,
        backorder_label: "Pre Order",
        id: 258929,
        sku: "LLOTNIG32259-18",
        backorder_type: "no_backorder",
      },
      {
        backorder_note: null,
        size: "20",
        color: "beige",
        parent_sku: "LLOTNIG32258",
        qty: 25,
        backorder_label: "Pre Order",
        id: 258930,
        sku: "LLOTNIG32259-20",
        backorder_type: "no_backorder",
      },
      {
        backorder_note: null,
        size: "22",
        color: "beige",
        parent_sku: "LLOTNIG32258",
        qty: 26,
        backorder_label: "Pre Order",
        id: 258931,
        sku: "LLOTNIG32259-22",
        backorder_type: "no_backorder",
      },
      {
        backorder_note: null,
        size: "24",
        color: "beige",
        parent_sku: "LLOTNIG32258",
        qty: 19,
        backorder_label: "Pre Order",
        id: 258932,
        sku: "LLOTNIG32259-24",
        backorder_type: "no_backorder",
      },
      {
        backorder_note: null,
        size: "26",
        color: "beige",
        parent_sku: "LLOTNIG32258",
        qty: 7,
        backorder_label: "Pre Order",
        id: 258933,
        sku: "LLOTNIG32259-26",
        backorder_type: "no_backorder",
      },
      {
        backorder_note: null,
        size: "28",
        color: "beige",
        parent_sku: "LLOTNIG32258",
        qty: 8,
        backorder_label: "Pre Order",
        id: 258934,
        sku: "LLOTNIG32259-28",
        backorder_type: "no_backorder",
      },
      {
        backorder_note: null,
        size: "4",
        color: "pink",
        parent_sku: "LLOTNIG32256",
        qty: 4,
        backorder_label: "Pre Order",
        id: 258906,
        sku: "LLOTNIG32256-4",
        backorder_type: "no_backorder",
      },
      {
        backorder_note: null,
        size: "6",
        color: "pink",
        parent_sku: "LLOTNIG32256",
        qty: 30,
        backorder_label: "Pre Order",
        id: 258907,
        sku: "LLOTNIG32256-6",
        backorder_type: "no_backorder",
      },
      {
        backorder_note: null,
        size: "8",
        color: "pink",
        parent_sku: "LLOTNIG32256",
        qty: 72,
        backorder_label: "Pre Order",
        id: 258908,
        sku: "LLOTNIG32256-8",
        backorder_type: "no_backorder",
      },
      {
        backorder_note: null,
        size: "10",
        color: "pink",
        parent_sku: "LLOTNIG32256",
        qty: 153,
        backorder_label: "Pre Order",
        id: 258909,
        sku: "LLOTNIG32256-10",
        backorder_type: "no_backorder",
      },
      {
        backorder_note: null,
        size: "12",
        color: "pink",
        parent_sku: "LLOTNIG32256",
        qty: 115,
        backorder_label: "Pre Order",
        id: 258910,
        sku: "LLOTNIG32256-12",
        backorder_type: "no_backorder",
      },
      {
        backorder_note: null,
        size: "14",
        color: "pink",
        parent_sku: "LLOTNIG32256",
        qty: 83,
        backorder_label: "Pre Order",
        id: 258911,
        sku: "LLOTNIG32256-14",
        backorder_type: "no_backorder",
      },
      {
        backorder_note: null,
        size: "16",
        color: "pink",
        parent_sku: "LLOTNIG32256",
        qty: 55,
        backorder_label: "Pre Order",
        id: 258912,
        sku: "LLOTNIG32256-16",
        backorder_type: "no_backorder",
      },
      {
        backorder_note: null,
        size: "18",
        color: "pink",
        parent_sku: "LLOTNIG32256",
        qty: 65,
        backorder_label: "Pre Order",
        id: 258914,
        sku: "LLOTNIG32257-18",
        backorder_type: "no_backorder",
      },
      {
        backorder_note: null,
        size: "20",
        color: "pink",
        parent_sku: "LLOTNIG32256",
        qty: 35,
        backorder_label: "Pre Order",
        id: 258915,
        sku: "LLOTNIG32257-20",
        backorder_type: "no_backorder",
      },
      {
        backorder_note: null,
        size: "22",
        color: "pink",
        parent_sku: "LLOTNIG32256",
        qty: 35,
        backorder_label: "Pre Order",
        id: 258916,
        sku: "LLOTNIG32257-22",
        backorder_type: "no_backorder",
      },
      {
        backorder_note: null,
        size: "24",
        color: "pink",
        parent_sku: "LLOTNIG32256",
        qty: 28,
        backorder_label: "Pre Order",
        id: 258917,
        sku: "LLOTNIG32257-24",
        backorder_type: "no_backorder",
      },
      {
        backorder_note: null,
        size: "26",
        color: "pink",
        parent_sku: "LLOTNIG32256",
        qty: 7,
        backorder_label: "Pre Order",
        id: 258918,
        sku: "LLOTNIG32257-26",
        backorder_type: "no_backorder",
      },
      {
        backorder_note: null,
        size: "28",
        color: "pink",
        parent_sku: "LLOTNIG32256",
        qty: 8,
        backorder_label: "Pre Order",
        id: 258919,
        sku: "LLOTNIG32257-28",
        backorder_type: "no_backorder",
      },
    ],
    only_show_in_hidden_category: 0,
    colors: ["pink"],
    rrp: 40,
    product_type: ["Pyjamas"],
    sizes: [
      {
        backorder_note: null,
        updated_at: "2021-11-30T13:40:00.000Z",
        size: "4",
        qty: 4,
        backorder_label: "Pre Order",
        id: 258906,
        sku: "LLOTNIG32256-4",
        backorder_type: "no_backorder",
      },
      {
        backorder_note: null,
        updated_at: "2021-09-29T07:27:05.000Z",
        size: "6",
        qty: 30,
        backorder_label: "Pre Order",
        id: 258907,
        sku: "LLOTNIG32256-6",
        backorder_type: "no_backorder",
      },
      {
        backorder_note: null,
        updated_at: "2021-09-29T07:27:05.000Z",
        size: "8",
        qty: 72,
        backorder_label: "Pre Order",
        id: 258908,
        sku: "LLOTNIG32256-8",
        backorder_type: "no_backorder",
      },
      {
        backorder_note: null,
        updated_at: "2021-09-29T07:27:05.000Z",
        size: "10",
        qty: 153,
        backorder_label: "Pre Order",
        id: 258909,
        sku: "LLOTNIG32256-10",
        backorder_type: "no_backorder",
      },
      {
        backorder_note: null,
        updated_at: "2021-09-29T07:27:05.000Z",
        size: "12",
        qty: 115,
        backorder_label: "Pre Order",
        id: 258910,
        sku: "LLOTNIG32256-12",
        backorder_type: "no_backorder",
      },
      {
        backorder_note: null,
        updated_at: "2021-09-29T07:27:05.000Z",
        size: "14",
        qty: 83,
        backorder_label: "Pre Order",
        id: 258911,
        sku: "LLOTNIG32256-14",
        backorder_type: "no_backorder",
      },
      {
        backorder_note: null,
        updated_at: "2021-09-29T07:27:05.000Z",
        size: "16",
        qty: 55,
        backorder_label: "Pre Order",
        id: 258912,
        sku: "LLOTNIG32256-16",
        backorder_type: "no_backorder",
      },
      {
        backorder_note: null,
        updated_at: "2021-11-30T13:48:32.000Z",
        size: "18",
        qty: 65,
        backorder_label: "Pre Order",
        id: 258914,
        sku: "LLOTNIG32257-18",
        backorder_type: "no_backorder",
      },
      {
        backorder_note: null,
        updated_at: "2021-09-29T07:27:05.000Z",
        size: "20",
        qty: 35,
        backorder_label: "Pre Order",
        id: 258915,
        sku: "LLOTNIG32257-20",
        backorder_type: "no_backorder",
      },
      {
        backorder_note: null,
        updated_at: "2021-09-29T07:27:05.000Z",
        size: "22",
        qty: 35,
        backorder_label: "Pre Order",
        id: 258916,
        sku: "LLOTNIG32257-22",
        backorder_type: "no_backorder",
      },
      {
        backorder_note: null,
        updated_at: "2021-09-29T07:27:05.000Z",
        size: "24",
        qty: 28,
        backorder_label: "Pre Order",
        id: 258917,
        sku: "LLOTNIG32257-24",
        backorder_type: "no_backorder",
      },
      {
        backorder_note: null,
        updated_at: "2021-09-29T07:27:05.000Z",
        size: "26",
        qty: 7,
        backorder_label: "Pre Order",
        id: 258918,
        sku: "LLOTNIG32257-26",
        backorder_type: "no_backorder",
      },
      {
        backorder_note: null,
        updated_at: "2021-09-29T07:27:05.000Z",
        size: "28",
        qty: 8,
        backorder_label: "Pre Order",
        id: 258919,
        sku: "LLOTNIG32257-28",
        backorder_type: "no_backorder",
      },
    ],
    price: 40,
    shop_the_look: [
      "LLOTNIG32254",
      "LLOTNIG32260",
      "LLOTNIG32264",
      "LLOTNIG32262",
    ],
    name: "lorna luxe pink 'park avenue' satin piped long 5pc gift set",
    id: 258913,
    categories: [
      {
        path: "clothing",
        name: "Clothing",
        id: 10,
      },
      {
        path: "new",
        name: "New",
        id: 17,
      },
      {
        path: "occasion",
        name: "Occasions",
        id: 570,
      },
      {
        path: "occasion/christmas-shop",
        name: "Christmas Shop",
        id: 584,
      },
      {
        path: "clothing/nightwear",
        name: "Nightwear",
        id: 649,
      },
      {
        path: "occasion/christmas-gifts",
        name: "Christmas Gifts",
        id: 926,
      },
      {
        path: "lorna-luxe",
        name: "Lorna Luxe",
        id: 1010,
      },
      {
        path: "lorna-luxe/lorna-nightwear",
        name: "Lorna Nightwear",
        id: 1241,
      },
      {
        path: "lorna-luxe/lorna-pj-s",
        name: "Lorna PJ's",
        id: 1592,
      },
    ],
    sku: "LLOTNIG32256",
    prices: {
      AUD: {
        rrp: 90,
        price: 90,
      },
      EU: {
        rrp: 56,
        price: 56,
      },
      ITSAPP: {
        rrp: 40,
        price: 40,
      },
      EUR: {
        rrp: 56,
        price: 56,
      },
      GBP: {
        rrp: 40,
        price: 40,
      },
      AU: {
        rrp: 90,
        price: 90,
      },
      USD: {
        rrp: 50,
        price: 50,
      },
      GB: {
        rrp: 40,
        price: 40,
      },
      IE: {
        rrp: 56,
        price: 56,
      },
      US: {
        rrp: 50,
        price: 50,
      },
      IEITSAPP: {
        rrp: 56,
        price: 56,
      },
    },
    priceRange: {
      from: 40,
      to: 40,
    },
    live_date: "2011-12-15T10:40:07.000Z",
    publish_date: "2021-12-13T19:46:00.000Z",
  },
]

const search = async (searchTerm: string): Promise<Array<SearchHit>> => {
  throw new Error("Something went wrong with your search")
  return EXAMPLE_ITEMS
}

export default search
